# Generated by Django 2.2.6 on 2020-05-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0057_auto_20200427_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='build_param_bau_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='build_param_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='model_build_bau_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='model_build_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='optimization_bau_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='optimization_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='output_construction_bau_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='output_construction_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
