# Generated by Django 2.2.10 on 2020-05-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0059_auto_20200513_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='pyjulia_bau_activate_include_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='pyjulia_bau_reopt_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
